#!/usr/bin/env bash
# Copyright (c) 2023 Peter Morgan <peter.james.morgan@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

while true;
do

    psql --host=postgres postgres postgres<<EOF
    begin;

    with rows as
      (select * from randload tablesample bernoulli(1) limit 10)
        delete from randload
          where exists (select * from rows where rows.id = randload.id);

    with rows as
      (select * from randload tablesample bernoulli(1) limit 10)
        update randload set updated_time = now(), uuid = gen_random_uuid()
          where exists (select * from rows where rows.id = randload.id);

    insert into randload (x) select generate_series(1, 10);
    commit;
EOF

    sleep $((RANDOM % 5));

done
