---
services:
  grafana:
    image:
      grafana/grafana:${GRAFANA_VERSION:-9.3.6}
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_HIDE_VERSION: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/dashboards/home.json
      GF_LIVE_ALLOWED_ORIGINS: "https://*.preview.app.github.dev"
    volumes:
      - type: bind
        source: example/grafana/provisioning
        target: /etc/grafana/provisioning
      - type: bind
        source: example/grafana/dashboards
        target: /etc/dashboards
      - grafana:/var/lib/grafana
    pull_policy:
      ${PULL_POLICY:-missing}
    profiles:
      - monitoring
      - all
  prometheus:
    image:
      prom/prometheus:${PROMETHEUS_VERSION:-v2.42.0}
    ports:
      - 9090:9090
    configs:
      - source: prometheus_yml
        target: /etc/prometheus/prometheus.yml
    pull_policy:
      ${PULL_POLICY:-missing}
    profiles:
      - monitoring
      - all
  postgres:
    image:
      ${POSTGRES_IMAGE:-postgres:${POSTGRES_VERSION:-15.1}}
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    command:
      -c wal_level=logical
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - type: bind
        source: example/initdb.d/
        target: /docker-entrypoint-initdb.d/
      - type: bind
        source: example/data
        target: /mnt
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 5
    pull_policy:
      ${PULL_POLICY:-missing}
    profiles:
      - db
      - all
  load-generator:
    image:
      postgres:${POSTGRES_VERSION:-15.1}
    environment:
      PGPASSWORD: postgres
    command:
      /bin/randload
    volumes:
      - type: bind
        source: example/randload
        target: /bin/randload
    links:
      - postgres
    pull_policy:
      ${PULL_POLICY:-missing}
    profiles:
      - db
      - all
  pgec:
    image:
      ${PGEC_IMAGE:-ghcr.io/shortishly/pgec:${PGEC_VERSION:-latest}}
    environment:
      PGMP_DATABASE_HOSTNAME: postgres
      PGMP_DATABASE_PASSWORD: postgres
      PGMP_DATABASE_USER: postgres
      PGMP_REPLICATION_LOGICAL_PUBLICATION_NAMES: pub
      PGMP_SOCKET_TRACE: false
    ports:
      - 8080:80
      - 6379:6379
      - 9100:9100
      - 11211:11211
    links:
      - postgres
    pull_policy:
      ${PULL_POLICY:-always}
    profiles:
      - cache
      - all
configs:
  prometheus_yml:
    file: example/prometheus.yml
volumes:
  db:
    driver: local
  grafana:
    driver: local
