services:
  prometheus:
    image:
      prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./example/prometheus.yml:/etc/prometheus/prometheus.yml
    pull_policy:
      always
  postgres:
    image:
      postgres:15
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    command:
      -c wal_level=logical
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./example/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 5
    pull_policy:
      always
  pgec:
    image:
      ghcr.io/shortishly/pgec:develop
    environment:
      PGMP_REPLICATION_LOGICAL_PUBLICATION_NAMES: pub
      PGMP_DATABASE_USER: postgres
      PGMP_DATABASE_PASSWORD: postgres
      PGMP_DATABASE_HOSTNAME: postgres
    ports:
      - 8080:80
      - 9100:9100
      - 11211:11211
    links:
      - postgres
volumes:
  db:
    driver: local
