global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'pgec'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9100']
