{
 "title": "Home",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "api request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cowboy_request_count[$__rate_interval])",
     "legendFormat": "rest"
    },
    {
     "expr": "rate(mcd_tcp_connection_decode_count[$__rate_interval])",
     "legendFormat": "mcd"
    },
    {
     "expr": "rate(resp_connection_decode_count[$__rate_interval])",
     "legendFormat": "resp"
    }
   ]
  },
  {
   "title": "pgec cache",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgec_storage_cache_count{action=\"hit\"}[$__rate_interval]))",
     "legendFormat": "hit"
    },
    {
     "expr": "sum(rate(pgec_storage_cache_count{action=\"miss\"}[$__rate_interval]))",
     "legendFormat": "miss"
    },
    {
     "expr": "sum(rate(pgec_storage_cache_count{action=\"expired\"}[$__rate_interval]))",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(pgec_storage_cache_count{action=\"delete\"}[$__rate_interval]))",
     "legendFormat": "delete"
    },
    {
     "expr": "sum(rate(pgec_storage_cache_count{action=\"update\"}[$__rate_interval]))",
     "legendFormat": "update"
    },
    {
     "expr": "sum(rate(pgec_storage_cache_count{action=\"insert\"}[$__rate_interval]))",
     "legendFormat": "insert"
    }
   ]
  },
  {
   "title": "pgec storage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgec_storage_get_count[$__rate_interval]))",
     "legendFormat": "get"
    },
    {
     "expr": "sum(rate(pgec_storage_put_count[$__rate_interval]))",
     "legendFormat": "put"
    },
    {
     "expr": "sum(rate(pgec_storage_delete_count[$__rate_interval]))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "pgec replica",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgec_replica_reqids_size[$__rate_interval]))",
     "legendFormat": "storage queue"
    },
    {
     "expr": "sum(rate(pgec_replica_storage_count[$__rate_interval]))",
     "legendFormat": "storage complete"
    }
   ]
  },
  {
   "title": "pgmp tag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pgmp_socket_tag_msg_count[$__rate_interval])",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "pgmp replication",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgmp_mm_rep_delete_count[$__rate_interval]))",
     "legendFormat": "delete"
    },
    {
     "expr": "sum(rate(pgmp_mm_rep_insert_count[$__rate_interval]))",
     "legendFormat": "insert"
    },
    {
     "expr": "sum(rate(pgmp_mm_rep_update_count[$__rate_interval]))",
     "legendFormat": "update"
    },
    {
     "expr": "sum(rate(pgmp_mm_rep_begin_transaction_count[$__rate_interval]))",
     "legendFormat": "begin"
    },
    {
     "expr": "sum(rate(pgmp_mm_rep_commit_count[$__rate_interval]))",
     "legendFormat": "commit"
    }
   ]
  },
  {
   "title": "mcd bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mcd_tcp_connection_recv_bytes[$__rate_interval])",
     "legendFormat": "recv"
    },
    {
     "expr": "rate(mcd_tcp_connection_send_bytes[$__rate_interval])",
     "legendFormat": "send"
    }
   ]
  },
  {
   "title": "resp bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(resp_connection_recv_bytes[$__rate_interval])",
     "legendFormat": "recv"
    },
    {
     "expr": "rate(resp_connection_send_bytes[$__rate_interval])",
     "legendFormat": "send"
    }
   ]
  },
  {
   "title": "beam ports",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (rate(beam_ports[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "beam memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by(type) (beam_memory)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "mcd socket",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mcd_tcp_listener_bind_count[$__rate_interval])",
     "legendFormat": "bind"
    },
    {
     "expr": "rate(mcd_tcp_listener_listen_count[$__rate_interval])",
     "legendFormat": "listen"
    },
    {
     "expr": "rate(mcd_tcp_listener_open_count[$__rate_interval])",
     "legendFormat": "open"
    }
   ]
  },
  {
   "title": "pgmp bytes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pgmp_socket_recv_bytes[$__rate_interval])",
     "legendFormat": "recv"
    },
    {
     "expr": "rate(pgmp_socket_send_bytes[$__rate_interval])",
     "legendFormat": "send"
    }
   ]
  },
  {
   "title": "PGMP: PostgreSQL Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Begin Tx Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "rate(pgmp_mm_rep_begin_transaction_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Commit Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "targets": [
      {
       "expr": "rate(pgmp_mm_rep_commit_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Update Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "rate(pgmp_mm_rep_update_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Delete Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "rate(pgmp_mm_rep_delete_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Insert Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "rate(pgmp_mm_rep_insert_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Keep Alive Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "targets": [
      {
       "expr": "rate(pgmp_mm_rep_keepalive_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WAL Applied",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "targets": [
      {
       "expr": "rate(pgmp_mm_rep_wal_applied[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WAL Clock",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
     "targets": [
      {
       "expr": "rate(pgmp_mm_rep_wal_clock[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WAL Flushed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "targets": [
      {
       "expr": "rate(pgmp_mm_rep_wal_flushed[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WAL Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "targets": [
      {
       "expr": "rate(pgmp_mm_rep_wal_received[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "PGMP: PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tagged Message Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "rate(pgmp_socket_tag_msg_bytes[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Parse Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
     "targets": [
      {
       "expr": "rate(pgmp_mm_parse_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bind Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "rate(pgmp_mm_bind_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Execute Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "targets": [
      {
       "expr": "rate(pgmp_mm_execute_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Socket Send Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "targets": [
      {
       "expr": "rate(pgmp_socket_send_bytes[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Query Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
     "targets": [
      {
       "expr": "rate(pgmp_mm_query_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Socket Receive Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
     "targets": [
      {
       "expr": "rate(pgmp_socket_recv_bytes[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Describe Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
     "targets": [
      {
       "expr": "rate(pgmp_mm_describe_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Socket Connect Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "targets": [
      {
       "expr": "rate(pgmp_socket_connect_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Socket Open Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
     "targets": [
      {
       "expr": "rate(pgmp_socket_open_count[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "BEAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "targets": [
      { "expr": "beam_processes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Ports",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "targets": [
      { "expr": "beam_ports", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "targets": [
      { "expr": "beam_memory", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}