{
 "title": "Redis API",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Connection Encode Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(resp_connection_encode_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Socket Receive Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(resp_connection_recv_bytes[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Decode Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(resp_connection_decode_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Socket Send Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(resp_connection_send_bytes[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}