#!/usr/bin/env bash
# Copyright (c) 2023 Peter Morgan <peter.james.morgan@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
. ../../paxtonhare/demo-magic/demo-magic.sh

DEMO_PROMPT="${GREEN}➜ ${CYAN}\W ${COLOR_RESET}"
unset DEMO_CMD_COLOR
PROMPT_TIMEOUT=3

# reset the grade back to C-
docker compose exec --no-TTY db psql --command="update grades set grade='C-' where ssn='234-56-7890'" > /dev/null


p "cat example/data/burkardt/grades.csv"
ack --passthru 234-56-7890 example/data/burkardt/grades.csv
p "cat example/initdb.d/010-grades.sql"
grep --invert-match '^--' example/initdb.d/010-grades.sql | ack --passthru "ssn text primary key"

p "curl -s http://localhost:8080/pub/grades/234-56-7890"
curl -s http://localhost:8080/pub/grades/234-56-7890 | jq | ack --passthru '\"C-\"'

p "redis-cli hgetall pub.grades.234-56-7890"
iredis HGETALL pub.grades.234-56-7890

pe "./bin/mcd-cli get pub.grades.234-56-7890"

p "update grades set grade='C' where ssn='234-56-7890'"
docker compose exec --no-TTY db psql --command="update grades set grade='C' where ssn='234-56-7890'"

p "curl -s http://localhost:8080/pub/grades/234-56-7890"
curl -s http://localhost:8080/pub/grades/234-56-7890 | jq | ack --passthru '\"C\"'

p "redis-cli hgetall pub.grades.234-56-7890"
iredis HGETALL pub.grades.234-56-7890

pe "./bin/mcd-cli get pub.grades.234-56-7890"

p "cat example/data/burkardt/cities.csv"
ack --after-context=3 --before-context=3 '\"Tulsa\",OK' example/data/burkardt/cities.csv

p "cat example/initdb.d/010-cities.sql"
grep --invert-match '^--' example/initdb.d/010-cities.sql | ack --passthru 'city|state'

pe "curl -s http://localhost:8080/pub/cities/Tulsa/OK | jq"

p "redis-cli hgetall pub.cities.Tulsa/OK"
iredis HGETALL pub.cities.Tulsa/OK

pe "./bin/mcd-cli get pub.cities.Tulsa/OK"

wait

echo
echo
