---
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make deps app dialyze eunit
      - name: PostgreSQL wal_level = logical
        run: |
          sudo pg_conftool set wal_level logical
      - name: Start PostgreSQL service
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create PostgreSQL ci user
        run: |
          sudo -u postgres psql --command="create user ci password 'ci' superuser replication"
      - name: Common Test
        run: make ct
        env:
          PGMP_PGMP_REPLICATION_ENABLED: false
          PGMP_DATABASE_USER: ci
          PGMP_DATABASE_NAME: postgres
          PGMP_DATABASE_PASSWORD: ci
          PGEC_HTTP_PORT: 8080
      - uses: actions/upload-artifact@v3
        with:
          name: ct-logs
          path: logs
      - name: Beam Docker Release
        uses: shortishly/beam-docker-release-action@v1.22
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          build-image: erlang:25.1
          build-platforms: linux/amd64
          build-tags: ghcr.io/${{github.repository}}:${{github.ref_name}}
